baseURL = 'https://unamonke.github.io/portfolio/'
languageCode = 'ru-ru'
title = 'Сергей Голованов'
theme = 'hugo-theme-console'

[params]
  description = "Your site description"
  animateStyle = "animate-fade-up" # Animation style for content


[[params.navlinks]]
  name = "Работа на площадке"
  url = "works_on_set/"

[[params.navlinks]]
  name = "Работа на постпродакшене"
  url = "works_on_post/"

[[params.navlinks]]
  name = "Контакты"
  url = "contacts/"